-- Create virtual warehouse (XS size to minimize credit usage)
CREATE WAREHOUSE IF NOT EXISTS CRYPTO_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Create main database
CREATE DATABASE IF NOT EXISTS CRYPTO_DB;

-- Create schemas for medallion architecture
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS CRYPTO_DB.GOLD;